# config.yaml
Path:
  kaggle-toxic-comment-directory: "/Users/ashiq/Documents/VTech/Security Analytics/Project5984/dataset/"
  kaggle-toxic-comment:
    train: "dataset/train-short.csv"
    test: "dataset/test-short.csv"
  OutputFileName:
    train: 'train-short.csv'
    test: 'test-short.csv'
peek-which: "train.csv"  # which datafile to peek
